run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - gofmt

linters-settings:
  gosec:
    severity: medium
  misspell:
    locale: US

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
